version: '2'
services:
  web:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    container_name: lunch-node
    ports:
      - "3000:3000"
    env_file: '.env.prod'
  db:
    image: postgres:9.5.1
    ports:
      - "5432:5432"
    container_name: lunch-postgres
    env_file: '.env.prod'